export const START_REGISTRATION = 'START_REGISTRATION';
export const REGISTRATION_MAIL_SUCCESS = 'REGISTRATION_MAIL_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';
export const VERIFYING_EMAIL = 'VERIFYING_EMAIL';

export const SET_SUCCESS = 'SET_SUCCESS';
export const SET_ERROR = 'SET_ERROR';